
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


0it [00:00, ?it/s]1it [00:00,  1.69it/s]2it [00:01,  1.64it/s]3it [00:02,  1.20it/s]4it [00:03,  1.05s/it]5it [00:05,  1.28s/it]6it [00:07,  1.46s/it]7it [00:09,  1.59s/it]8it [00:11,  1.70s/it]9it [00:12,  1.79s/it]10it [00:15,  1.87s/it]11it [00:17,  1.95s/it]12it [00:19,  2.00s/it]13it [00:21,  2.06s/it]14it [00:23,  2.10s/it]15it [00:25,  2.13s/it]16it [00:28,  2.23s/it]16it [00:28,  1.77s/it]
  0%|                                                                                              | 0/14 [00:00<?, ?it/s]  7%|██████                                                                               | 1/14 [02:08<27:47, 128.31s/it] 14%|████████████▏                                                                        | 2/14 [04:50<29:35, 147.98s/it] 21%|██████████████████▏                                                                  | 3/14 [08:07<31:14, 170.39s/it] 29%|████████████████████████▎                                                            | 4/14 [11:36<30:56, 185.68s/it] 36%|██████████████████████████████▎                                                      | 5/14 [16:22<33:17, 221.97s/it] 43%|████████████████████████████████████▍                                                | 6/14 [21:17<32:53, 246.73s/it] 43%|████████████████████████████████████▍                                                | 6/14 [21:31<28:41, 215.23s/it]
Traceback (most recent call last):
  File "/home/users/delon/aemulusnu_massfunction/1.parse_data/prepare_data.py", line 167, in <module>
    assert(len(bin_idx) == len(snapshot_pos))
AssertionError
