
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


  0%|                                                                                               | 0/4 [00:00<?, ?it/s] 25%|█████████████████████▊                                                                 | 1/4 [00:19<00:59, 19.81s/it] 50%|███████████████████████████████████████████▌                                           | 2/4 [00:33<00:31, 16.00s/it] 75%|█████████████████████████████████████████████████████████████████▎                     | 3/4 [00:46<00:14, 14.77s/it]100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:01<00:00, 14.74s/it]100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:01<00:00, 15.29s/it]
  0%|                                                                                               | 0/4 [00:00<?, ?it/s] 25%|█████████████████████▊                                                                 | 1/4 [00:20<01:02, 20.75s/it] 50%|███████████████████████████████████████████▌                                           | 2/4 [00:34<00:33, 16.81s/it] 75%|█████████████████████████████████████████████████████████████████▎                     | 3/4 [00:48<00:15, 15.21s/it]100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:02<00:00, 14.73s/it]100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:02<00:00, 15.52s/it]
  0%|                                                                                               | 0/4 [00:00<?, ?it/s] 25%|█████████████████████▊                                                                 | 1/4 [00:20<01:02, 20.78s/it] 50%|███████████████████████████████████████████▌                                           | 2/4 [00:36<00:35, 17.66s/it] 75%|█████████████████████████████████████████████████████████████████▎                     | 3/4 [00:49<00:15, 15.68s/it]100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:00<00:00, 13.85s/it]100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:00<00:00, 15.16s/it]
  0%|                                                                                               | 0/4 [00:00<?, ?it/s] 25%|█████████████████████▊                                                                 | 1/4 [00:20<01:02, 20.79s/it] 50%|███████████████████████████████████████████▌                                           | 2/4 [00:36<00:35, 17.87s/it] 75%|█████████████████████████████████████████████████████████████████▎                     | 3/4 [00:50<00:16, 16.27s/it]100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:07<00:00, 16.27s/it]100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:07<00:00, 16.81s/it]
Traceback (most recent call last):
  File "/home/users/delon/aemulusnu_massfunction/4.fisher_forecast/tinker_forecast/compute_cluster_abundance_cov_tinker.py", line 179, in <module>
    options={'limit':quad_limit, 'epsrel': 5e-3, 'epsabs': 0}
NameError: name 'quad_limit' is not defined
Exception ignored in: <function Cosmology.__del__ at 0x7f1d61c19550>
Traceback (most recent call last):
  File "/home/users/delon/.local/lib/python3.9/site-packages/pyccl/cosmology.py", line 504, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Pk2D.__del__ at 0x7f1d64bb8040>
Traceback (most recent call last):
  File "/home/users/delon/.local/lib/python3.9/site-packages/pyccl/pk2d.py", line 345, in __del__
TypeError: 'NoneType' object is not callable
