
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


/home/users/delon/aemulusnu_massfunction/fit.py:76: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  res, err = quad(dσ2dk, 0, np.inf)
  0%|          | 0/16 [00:00<?, ?it/s]/home/users/delon/aemulusnu_massfunction/fit.py:76: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  res, err = quad(dσ2dk, 0, np.inf)
/home/users/delon/aemulusnu_massfunction/fit.py:116: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  res, err = quad(dσ2dRdk, 0, np.inf)
  6%|▋         | 1/16 [00:09<02:22,  9.50s/it] 12%|█▎        | 2/16 [00:18<02:12,  9.49s/it] 19%|█▉        | 3/16 [00:28<02:04,  9.57s/it] 25%|██▌       | 4/16 [00:38<01:55,  9.62s/it] 31%|███▏      | 5/16 [00:48<01:45,  9.63s/it] 38%|███▊      | 6/16 [00:57<01:36,  9.65s/it] 44%|████▍     | 7/16 [01:07<01:26,  9.67s/it] 50%|█████     | 8/16 [01:17<01:17,  9.70s/it] 56%|█████▋    | 9/16 [01:26<01:07,  9.71s/it] 62%|██████▎   | 10/16 [01:36<00:58,  9.69s/it] 69%|██████▉   | 11/16 [01:46<00:48,  9.68s/it] 75%|███████▌  | 12/16 [01:55<00:38,  9.68s/it] 81%|████████▏ | 13/16 [02:05<00:28,  9.66s/it] 88%|████████▊ | 14/16 [02:15<00:19,  9.68s/it] 94%|█████████▍| 15/16 [02:24<00:09,  9.68s/it]100%|██████████| 16/16 [02:34<00:00,  9.69s/it]100%|██████████| 16/16 [02:34<00:00,  9.66s/it]
Traceback (most recent call last):
  File "/home/users/delon/aemulusnu_massfunction/fit.py", line 479, in <module>
    jack_covs = {a:jackknife[a][1] for a in N_data}
  File "/home/users/delon/aemulusnu_massfunction/fit.py", line 479, in <dictcomp>
    jack_covs = {a:jackknife[a][1] for a in N_data}
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
